/**
 * Realistic seed data & Simulation scenarios for Jal Rakshak AI
 */

export const INITIAL_RIVERS = [
  {
    id: 'mahanadi-naraj',
    name: 'Mahanadi (Naraj Barrage, Cuttack)',
    state: 'Odisha',
    currentLevel: 26.85,
    warningLevel: 25.41,
    dangerLevel: 26.41,
    status: 'CRITICAL',
    trend: 'RISING',
    inflow: '11.45 Lakh Cusecs',
    outflow: '11.20 Lakh Cusecs',
    gatesOpen: '28 / 64 Gates',
  },
  {
    id: 'brahmani-jenapur',
    name: 'Brahmani (Jenapur Gauge)',
    state: 'Odisha',
    currentLevel: 67.20,
    warningLevel: 66.00,
    dangerLevel: 67.00,
    status: 'HIGH',
    trend: 'RISING',
    inflow: '3.80 Lakh Cusecs',
    outflow: '3.75 Lakh Cusecs',
    gatesOpen: '14 / 24 Gates',
  },
  {
    id: 'baitarani-akhua',
    name: 'Baitarani (Akhuapada Station)',
    state: 'Odisha',
    currentLevel: 18.10,
    warningLevel: 17.83,
    dangerLevel: 18.00,
    status: 'CRITICAL',
    trend: 'STABLE',
    inflow: '1.95 Lakh Cusecs',
    outflow: '1.90 Lakh Cusecs',
    gatesOpen: 'All open',
  },
  {
    id: 'ganga-patna',
    name: 'Ganga (Digha Ghat, Patna)',
    state: 'Bihar',
    currentLevel: 50.12,
    warningLevel: 49.50,
    dangerLevel: 50.50,
    status: 'MEDIUM',
    trend: 'RISING',
    inflow: '7.20 Lakh Cusecs',
    outflow: '7.10 Lakh Cusecs',
    gatesOpen: 'Normal flow',
  },
  {
    id: 'yamuna-delhi',
    name: 'Yamuna (Old Railway Bridge, Delhi)',
    state: 'Delhi',
    currentLevel: 205.80,
    warningLevel: 204.50,
    dangerLevel: 205.33,
    status: 'HIGH',
    trend: 'FALLING',
    inflow: '1.45 Lakh Cusecs',
    outflow: '1.40 Lakh Cusecs',
    gatesOpen: 'Hathnikund barrage controlled',
  },
]

export const INITIAL_FORECAST_TIMELINE = [
  { time: 'Now', timeLabel: 'Current', rainMm: 42, waterLevel: 26.85, riskScore: 88, status: 'CRITICAL' },
  { time: '+3h', timeLabel: '21:00', rainMm: 65, waterLevel: 27.15, riskScore: 94, status: 'CRITICAL' },
  { time: '+6h', timeLabel: '00:00 (Peak)', rainMm: 80, waterLevel: 27.40, riskScore: 98, status: 'CRITICAL' },
  { time: '+12h', timeLabel: '06:00', rainMm: 35, waterLevel: 26.90, riskScore: 82, status: 'CRITICAL' },
  { time: '+18h', timeLabel: '12:00', rainMm: 15, waterLevel: 26.10, riskScore: 68, status: 'HIGH' },
  { time: '+24h', timeLabel: '18:00', rainMm: 8, waterLevel: 25.30, riskScore: 48, status: 'MEDIUM' },
]

export const INITIAL_SHELTERS = [
  {
    id: 'SH-01',
    name: 'Barabati Multi-Purpose Cyclone & Flood Shelter',
    locationName: 'Bidanasi, Cuttack',
    lat: 20.4812,
    lng: 85.8654,
    distanceKm: 1.8,
    capacity: 1200,
    currentOccupancy: 840,
    status: 'ACTIVE',
    riskLevel: 'LOW',
    isRecommended: true,
    phone: '+91 671 2304921',
    facilities: ['Medical Aid Camp', 'Drinking Water Plant', '24/7 Diesel Generator', 'Community Kitchen', 'Women & Child Room'],
    elevationMeters: 38,
    roadCondition: 'Safe & Clear (Elevated Ring Road)',
  },
  {
    id: 'SH-02',
    name: 'Ravenshaw University Relief Shelter Complex',
    locationName: 'College Square, Cuttack',
    lat: 20.4638,
    lng: 85.8942,
    distanceKm: 3.4,
    capacity: 2500,
    currentOccupancy: 1980,
    status: 'ACTIVE',
    riskLevel: 'LOW',
    isRecommended: true,
    phone: '+91 671 2201987',
    facilities: ['Field Hospital', 'Helipad Access', 'Clean Water', 'Food Packets', 'Power Backup', 'Livestock Enclosure'],
    elevationMeters: 41,
    roadCondition: 'Passable via Badambadi Overbridge',
  },
  {
    id: 'SH-03',
    name: 'Kendrapara Town High School Shelter',
    locationName: 'Marsaghai, Kendrapara',
    lat: 20.5015,
    lng: 86.4210,
    distanceKm: 12.5,
    capacity: 800,
    currentOccupancy: 760,
    status: 'NEAR_FULL',
    riskLevel: 'MEDIUM',
    isRecommended: false,
    phone: '+91 6727 220114',
    facilities: ['First Aid', 'Dry Ration Packets', 'Solar Lighting'],
    elevationMeters: 24,
    roadCondition: 'Waterlogged at outer approach (Use Tractor/Boats)',
  },
  {
    id: 'SH-04',
    name: 'Bhubaneswar KIIT Disaster Relief Center',
    locationName: 'Patia, Bhubaneswar',
    lat: 20.3541,
    lng: 85.8192,
    distanceKm: 22.0,
    capacity: 3500,
    currentOccupancy: 1120,
    status: 'ACTIVE',
    riskLevel: 'LOW',
    isRecommended: true,
    phone: '+91 674 2725113',
    facilities: ['State-of-art Medical Ward', 'Ambulance Station', 'Hot Meals', 'Sanitation Kits', 'Wi-Fi Emergency Mesh'],
    elevationMeters: 55,
    roadCondition: 'All NH16 High-Speed Routes Open',
  },
  {
    id: 'SH-05',
    name: 'Banki Sub-Divisional Flood Shelter',
    locationName: 'Banki, Mahanadi Bank',
    lat: 20.3802,
    lng: 85.5312,
    distanceKm: 18.2,
    capacity: 650,
    currentOccupancy: 650,
    status: 'FULL',
    riskLevel: 'HIGH',
    isRecommended: false,
    phone: '+91 671 2894102',
    facilities: ['Basic First Aid', 'Purified Water'],
    elevationMeters: 30,
    roadCondition: 'Access road submerged by 0.6m; NDRF boats assisting',
  },
]

export const INITIAL_REPORTS = [
  {
    id: 'REP-401',
    user: 'Subhasish Dash',
    location: 'Bidanasi Embankment, Cuttack',
    lat: 20.4795,
    lng: 85.8521,
    waterDepth: '1.2 meters (Waist Level)',
    category: 'Embankment Seepage & Road Cutoff',
    description: 'Mahanadi backwater is breaching near the sluice gate. 20 houses inundated in lower ward.',
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
    verified: true,
    aiConfidence: 96,
    aiDetectedDepth: '1.18 meters',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    trappedPeople: 45,
    needsBoat: true,
    status: 'VERIFIED',
  },
  {
    id: 'REP-402',
    user: 'Priyanka Mohapatra',
    location: 'Jobra Barrage Road, Cuttack',
    lat: 20.4682,
    lng: 85.8995,
    waterDepth: '0.6 meters (Knee Level)',
    category: 'Waterlogged Main Arterial Road',
    description: 'Drainage overflowed onto the highway. Sedans and autos stuck. NDRF barricading lane.',
    imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    verified: true,
    aiConfidence: 91,
    aiDetectedDepth: '0.58 meters',
    timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
    trappedPeople: 0,
    needsBoat: false,
    status: 'VERIFIED',
  },
  {
    id: 'REP-403',
    user: 'Alok Jena',
    location: 'Marsaghai Canal Bridge, Kendrapara',
    lat: 20.4988,
    lng: 86.4150,
    waterDepth: '1.8 meters (Chest Level)',
    category: 'Trapped Families on Roof',
    description: '3 families with infants are waving red cloths from the rooftop of community center.',
    imageUrl: 'https://images.unsplash.com/photo-1600336153113-d66c79de3e91?auto=format&fit=crop&w=800&q=80',
    verified: true,
    aiConfidence: 98,
    aiDetectedDepth: '1.85 meters',
    timestamp: new Date(Date.now() - 75 * 60000).toISOString(),
    trappedPeople: 14,
    needsBoat: true,
    status: 'ESCALATED_TO_RESCUE',
  },
  {
    id: 'REP-404',
    user: 'Rakesh Sahoo',
    location: 'Athagarh Riverside Hamlet',
    lat: 20.5310,
    lng: 85.7820,
    waterDepth: '0.4 meters (Ankle-Knee)',
    category: 'Rising Groundwater & Crop Submersion',
    description: 'Paddy fields fully submerged. Village access path getting slippery.',
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    verified: false,
    aiConfidence: 84,
    aiDetectedDepth: '0.35 meters',
    timestamp: new Date(Date.now() - 110 * 60000).toISOString(),
    trappedPeople: 0,
    needsBoat: false,
    status: 'PENDING_REVIEW',
  },
]

export const INITIAL_EMERGENCIES = [
  {
    id: 'SOS-8801',
    category: 'Rooftop Stranded + Infants',
    priority: 'CRITICAL',
    priorityScore: 97,
    location: 'Bidanasi Lower Basti, Ward 4, Cuttack',
    lat: 20.4798,
    lng: 85.8510,
    peopleCount: 8,
    victims: { infants: 2, children: 1, adults: 3, elderly: 2, pregnant: 0 },
    waterDepth: '2.1 meters (First floor inundated)',
    description: 'Water reached 1st floor ceiling. Family shifted to roof. No drinking water for 8 hours. Flashlights active.',
    contactName: 'Debendra Swain',
    contactPhone: '+91 98610 23412',
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    assignedTeam: 'NDRF Unit 07 (Bravo Boat)',
    status: 'IN_PROGRESS',
    etaMinutes: 14,
  },
  {
    id: 'SOS-8802',
    category: 'Critical Medical (Dialysis Patient)',
    priority: 'CRITICAL',
    priorityScore: 99,
    location: 'Near Old Jagannath Road, Chauliaganj',
    lat: 20.4590,
    lng: 85.9120,
    peopleCount: 3,
    victims: { infants: 0, children: 0, adults: 2, elderly: 1, pregnant: 0 },
    waterDepth: '1.4 meters',
    description: 'Patient 68yo missed dialysis today. Oxygen concentrator running on dying battery. Urgent boat stretcher needed.',
    contactName: 'Mamata Panda',
    contactPhone: '+91 94370 88219',
    timestamp: new Date(Date.now() - 28 * 60000).toISOString(),
    assignedTeam: 'ODRAF Quick Response 02',
    status: 'ON_SCENE',
    etaMinutes: 2,
  },
  {
    id: 'SOS-8803',
    category: 'Collapsed Boundary Wall & Rising Surge',
    priority: 'HIGH',
    priorityScore: 82,
    location: 'Tulasipur Riverfront Colony, Cuttack',
    lat: 20.4850,
    lng: 85.8590,
    peopleCount: 6,
    victims: { infants: 1, children: 2, adults: 3, elderly: 0, pregnant: 1 },
    waterDepth: '1.1 meters',
    description: 'Compound wall gave way under river backwater surge. Family standing on wooden tables.',
    contactName: 'Niranjan Behera',
    contactPhone: '+91 99371 54820',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    assignedTeam: 'SDRF Alpha Squad',
    status: 'DISPATCHED',
    etaMinutes: 22,
  },
  {
    id: 'SOS-8804',
    category: 'Elderly Couple Stranded with Pets',
    priority: 'MEDIUM',
    priorityScore: 68,
    location: 'Nuapatna Weaver Cluster, Cuttack Outer',
    lat: 20.5120,
    lng: 85.7980,
    peopleCount: 2,
    victims: { infants: 0, children: 0, adults: 0, elderly: 2, pregnant: 0 },
    waterDepth: '0.8 meters',
    description: 'Power cut off, water entered ground floor. Couple is mobile but unable to wade through strong current.',
    contactName: 'Anasuya Das',
    contactPhone: '+91 97760 19022',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    assignedTeam: null,
    status: 'PENDING_ASSIGNMENT',
    etaMinutes: null,
  },
]

export const INITIAL_RESCUE_TEAMS = [
  {
    id: 'TEAM-NDRF-07',
    name: 'NDRF 03rd Battalion (Unit 07 - Bravo)',
    commander: 'Inspector Vikram Rathore',
    phone: '+91 98110 54321',
    unitType: 'Inflatable Motor Boat (IRB) & Dive Team',
    capacityPersons: 16,
    currentLocation: 'Bidanasi Ghat Basecamp',
    lat: 20.4820,
    lng: 85.8610,
    status: 'ON_MISSION',
    activeMissionId: 'SOS-8801',
    equipment: ['2x Gemini 40HP Inflatable Boats', '12x Life Jackets', 'Satellite Comm Radio', 'First Aid Trauma Kit', 'Hydraulic Cutters'],
  },
  {
    id: 'TEAM-ODRAF-02',
    name: 'ODRAF Specialized Unit 02 (Medical Evac)',
    commander: 'Sub-Inspector Tapas Nayak',
    phone: '+91 94371 99012',
    unitType: 'Heavy Rescue Amphibious Craft',
    capacityPersons: 12,
    currentLocation: 'Chauliaganj Embankment Point',
    lat: 20.4610,
    lng: 85.9080,
    status: 'ON_SCENE',
    activeMissionId: 'SOS-8802',
    equipment: ['Amphibious Stretcher Craft', 'Portable Oxygen Cylinder', 'AED Defibrillator', 'Floating Rope Throw Bags'],
  },
  {
    id: 'TEAM-SDRF-ALPHA',
    name: 'SDRF Team Alpha (Evacuation Support)',
    commander: 'Officer Sangram Rout',
    phone: '+91 99380 44109',
    unitType: 'High-Clearance 4x4 Truck + FRP Rescue Boat',
    capacityPersons: 20,
    currentLocation: 'Tulasipur Cantonment Road',
    lat: 20.4880,
    lng: 85.8650,
    status: 'DISPATCHED',
    activeMissionId: 'SOS-8803',
    equipment: ['FRP Rigid Rescue Boat', 'Searchlights (5000 Lumens)', 'Life Buoys', 'Megaphones'],
  },
  {
    id: 'TEAM-VOLUNTEER-01',
    name: 'Civil Defense Volunteer Boat Group',
    commander: 'Captain (Retd.) A. K. Patnaik',
    phone: '+91 94380 11223',
    unitType: 'Country Motorized Boats (x3)',
    capacityPersons: 24,
    currentLocation: 'Jobra Barrage Staging Area',
    lat: 20.4690,
    lng: 85.8980,
    status: 'STANDBY_READY',
    activeMissionId: null,
    equipment: ['3x Motorized River Country Crafts', '30x Life Vests', 'Dry Food & Water Crates'],
  },
]

export const RISK_POLYGONS = [
  {
    id: 'ZONE-RED-01',
    name: 'Mahanadi Lower Basin - Bidanasi to Nuapatna',
    severity: 'CRITICAL',
    score: 94,
    color: '#DC2626',
    fillOpacity: 0.45,
    waterDepth: '1.2m - 2.4m',
    populationAtRisk: '34,500',
    status: 'EVACUATION_MANDATORY',
    coordinates: [
      [20.475, 85.845],
      [20.490, 85.855],
      [20.495, 85.875],
      [20.482, 85.885],
      [20.468, 85.865],
    ]
  },
  {
    id: 'ZONE-ORANGE-02',
    name: 'Kathajodi River Front - Chauliaganj & Khan Nagar',
    severity: 'HIGH',
    score: 74,
    color: '#EA580C',
    fillOpacity: 0.35,
    waterDepth: '0.5m - 1.2m',
    populationAtRisk: '22,000',
    status: 'HIGH_ALERT_PREPAREDNESS',
    coordinates: [
      [20.450, 85.885],
      [20.465, 85.905],
      [20.460, 85.930],
      [20.445, 85.920],
      [20.440, 85.895],
    ]
  },
  {
    id: 'ZONE-YELLOW-03',
    name: 'Puri Lowland Catchment - Nimapara & Gop',
    severity: 'MEDIUM',
    score: 52,
    color: '#CA8A04',
    fillOpacity: 0.30,
    waterDepth: '0.2m - 0.5m',
    populationAtRisk: '15,800',
    status: 'WATCH_AND_PREPARE',
    coordinates: [
      [20.380, 85.890],
      [20.410, 85.920],
      [20.395, 85.960],
      [20.365, 85.940],
    ]
  },
  {
    id: 'ZONE-GREEN-04',
    name: 'Bhubaneswar High-Ground Plateau (Patia / Chandaka)',
    severity: 'LOW',
    score: 18,
    color: '#16A34A',
    fillOpacity: 0.20,
    waterDepth: '0.0m (Dry & Elevated)',
    populationAtRisk: '0',
    status: 'SAFE_EVACUATION_DESTINATION',
    coordinates: [
      [20.340, 85.800],
      [20.370, 85.810],
      [20.365, 85.845],
      [20.335, 85.835],
    ]
  }
]

export const DEMO_ACCOUNTS = {
  citizen: {
    id: 'USR-CIT-01',
    name: 'Ramesh Mohanty',
    email: 'ramesh.citizen@jalrakshak.org',
    role: 'citizen',
    phone: '+91 98612 34567',
    district: 'Cuttack',
    state: 'Odisha',
    location: { lat: 20.4782, lng: 85.8621, address: 'Bidanasi, Cuttack' },
    familyMembers: 4,
  },
  admin: {
    id: 'USR-ADM-01',
    name: 'Dr. Anita Sharma (IAS)',
    email: 'anita.src@odisha.gov.in',
    role: 'admin',
    phone: '+91 674 2534100',
    district: 'State Disaster Ops Center',
    designation: 'Special Relief Commissioner (SRC)',
    state: 'Odisha',
  },
  rescue: {
    id: 'USR-RES-01',
    name: 'Cmdr. Vikram Rathore',
    email: 'vikram.ndrf@gov.in',
    role: 'rescue',
    unitId: 'TEAM-NDRF-07',
    phone: '+91 98110 54321',
    battalion: '03rd NDRF Battalion, Mundali',
    state: 'Odisha',
  }
}
